import type { Metadata } from 'next'
import localFont from 'next/font/local'

import '../shared/styles/global.scss'

const Satoshi = localFont({ src: '/fonts/satoshi/Satoshi-Medium.otf' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={Satoshi.className}>{children}</body>
    </html>
  )
}
